### ISSUE TITLE
Cannot compile in XUbuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by evandrix** [coolwanglu/vim.js#38]
The following error message appears repeatedly after typing `make`:

``` Shell
vim.h:398:61: fatal error: auto/osdef.h: No such file or directory
 # include "auto/osdef.h" /* bring missing declarations in */
```

**Comment by emnh** [comment]
Does "make proto" help?

**Comment by emnh** [comment]
I thought maybe it was similar to #21, but maybe not.

**Comment by coolwanglu** [comment]
I remember there's a utility there to generate this file, probably also in `auto/`.

**Comment by evandrix** [comment]
@emnh: No, `make proto` not only doesn't help, it also reports the same error of the missing `auto/osdef.h`.

@coolwanglu: No, there's only mainly `configure`, and it's associated files @ `src/auto`.

**Comment by coolwanglu** [comment]
@evandrix I don't remember it clearly, but if you search for "osdef.h" in `Makefile` or probably `auto/Makefile`, you might be able to find the corresponding script to generate that file.

**Comment by evandrix** [comment]
@coolwanglu: yes, you're right.

proceeded past that `auto/osdef.h` error, now faced with:

```
proto.h:216:22: fatal error: pty.pro: No such file or directory
 #   include "pty.pro"
```

`make proto` didn't help.

**Comment by evandrix** [comment]
found it in vim v7.4 source code which I downloaded separately. where's that meant to go, relative to the project root of vim.js?

**Comment by coolwanglu** [comment]
That must be #21, you need to configure it with gcc, and run `make proto` to generate those files.

**Comment by evandrix** [comment]
Yep, managed to resolve that error too; now `make` completes successfully. thanks for your help.

After that, am I supposed to run `build.sh`? Then what, how do I "run" it? Where's the "index.html"?

**Comment by coolwanglu** [comment]
@evandrix `build.sh` is what I'm using to build the project, I might enable or disable some phases time to time. You should probably read it and get a rough idea of the steps.

Everything about the web go into `web/`

**Comment by evandrix** [comment]
so is it the case that only `make` is necessary, and `build.sh` is optional?

**Comment by coolwanglu** [comment]
Right.

**Comment by evandrix** [comment]
ok, now i'm just facing llvm version incompatibility with `emscripten/emcc`; but that's not your repo's problem, so i'm closing this issue. ta
